# Generated by Django 5.0.6 on 2024-08-28 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_boss_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boss',
            options={'verbose_name_plural': 'boss'},
        ),
    ]
