# Generated by Django 5.1 on 2024-08-29 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_winner_vote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
    ]
