# Generated by Django 5.1 on 2024-08-29 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0009_alter_vote_customer_alter_vote_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
