export const CUSTOMER_SIGNUP_SUCCESS="CUSTOMER_SIGNUP_SUCCESS";
export const CUSTOMER_SIGUP_FAIL="CUSTOMER_SIGNUP_FAIL";
export const CUSTOMER_AUTHENTICATED_SUCCESS="CUSTOMER_AUTHENTICATED_SUCCESS";
export const CUSTOMER_AUTHENTICATED_FAILED="CUSTOMER_AUTHENTICATION_FAILED";
export const CUSTOMER_LOGIN_SUCCESS="CUSTOMER_LOGIN_SUCCESS";
export const CUSTOMER_LOGIN_FAIL="CUSTOMER_LOGIN_FAIL";

export const BOSS_SIGNUP_SUCCESS="BOSS_SIGNUP_SUCCESS";
export const BOSS_SIGUP_FAIL="BOSS_SIGNUP_FAIL";
export const BOSS_AUTHENTICATED_SUCCESS="BOSS_AUTHENTICATED_SUCCESS";
export const BOSS_AUTHENTICATED_FAILED="BOSS_AUTHENTICATION_FAILED";
export const BOSS_LOGIN_SUCCESS="BOSS_LOGIN_SUCCESS";
export const BOSS_LOGIN_FAIL="BOSS_LOGIN_FAIL";

export const EMAIL_VERIFY_SUCCESS="EMAIL_VERIFY_SUCCESS";
export const EMAIL_VERIFY_FAILED="EMAIL_VERIFY_FAILED";
export const CHANGE_PASSWORD_SUCCESS="CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILED="CHANGE_PASSWORD_FAILED";
export const LOGOUT="LOGOUT";